Update Circle and add Travis to generate documentation
mapbox/mapbox-gl-native-ios pull request #410
Opened 2020-09-02 16:46 UTC by katydecorah

In https://github.com/mapbox/documentation/issues/527, the docs team proposed that generated documentation could live in the `publisher-production` branches of the source repo.

This PR prepares Circle to handle this change, including:
- Add a new step in Circle to "Trigger documentation deploy steps"
  - Upon a new release, this step will trigger Travis to run in this repo.
  - Travis will then build the documentation and run a script to generate a PR against `publisher-production` with the generated documentation for the latest release.
- The original Circle job to "Trigger external deploy steps" will remain. This step will bump the constants and other metadata-related files in https://github.com/mapbox/ios-sdk.

## Notes

The `publisher-production` (and `publisher-staging`) branches will only contain the generated documentation and any files required to publish them: https://github.com/mapbox/mapbox-gl-native-ios/tree/publisher-staging

## To do
- [x] Enable Travis in this repo.
- [x] Add GitHub token to Travis settings.
- [x] Update ios-sdk Travis job to remove steps to build documentation and only update metadata files.
- [x] Determine: Could `docs-github-pull-request.js` be a package? Since we'll likely be using this in several repos, it would help reduce footprint in each repo.
- [x] Add @MapboxCI as contributor with write access to this repo.
- [ ] (?) Add script to push previous version to the S3 archive site.
- [x] Test the pipeline.
- [x] Add inline documentation to configuration files

## Publisher steps

- [x] Enable publisher on this repository
- [x] Register the repository under docs subdomain.
- [x] Create publisher-staging branch
- [x] Create publisher-production branch

## How to test

1. In Travis, click More Options > Trigger build.
2. Branch: `docs`
3. Custom commit mesage: `[maps] docs pipeline test`
4. Custom config:
```yml
merge_mode: deep_merge
env:
 - SDK_FLAVOR=maps RELEASE_TAG=6.1.0
```

---

cc @danswick

2020-09-10 19:22 UTC, katydecorah commented on .travis.yml
> +        - docs-release-pull-request -s $SDK_FLAVOR -t $RELEASE_TAG -b publisher-staging -p ios -r mapbox-gl-native-ios
Before merge, we can remove the branch flag (default is publisher-production)

```suggestion
        - docs-release-pull-request -s $SDK_FLAVOR -t $RELEASE_TAG -p ios -r mapbox-gl-native-ios
```

2020-09-14 13:51 UTC, katydecorah commented
I'm still stumped. Travis continues to error during `git push`:

> remote: Invalid username or password.

Since this script works in ios-sdk, I think it's related to permissions. I think we should double check that the `GITHUB_TOKEN` in the Travis configuration is correct. (@danswick can you help me with this one.)

2020-09-14 19:11 UTC, katydecorah commented
Update the GITHUB_TOKEN fixed the issue. We got a build in #435 

To do
- [ ] Fix label, it is currently "undefined".
- [ ] Only commit the generated api docs folder.

2020-09-14 19:33 UTC, katydecorah commented on scripts/docs-update-maps.sh
> +git checkout publisher-staging
```suggestion
git checkout publisher-production
```

To do before merge!

2020-09-14 20:30 UTC, katydecorah commented
I think I need to change the git depth for the shell scripts, it can't find `publisher-staging`

2020-09-15 16:35 UTC, katydecorah commented
The build at https://github.com/mapbox/mapbox-gl-native-ios/pull/446 worked great. I just added one more commit that adds `[ci skip]` to the commit message - this will prevent circle from running for these generated docs commits https://circleci.com/docs/2.0/skip-build/

2020-09-15 16:46 UTC, katydecorah commented on scripts/docs-update-maps.sh
> +git checkout origin/publisher-staging
Update this before merge:

```suggestion
git checkout origin/publisher-production
```

2020-09-15 17:06 UTC, katydecorah commented
@danswick I think this is ready for review!

Travis just completed a test PR at: https://github.com/mapbox/mapbox-gl-native-ios/pull/447

2020-09-30 19:55 UTC, danswick approved these changes
This looks great to me, @katydecorah 👍

2020-10-02 19:53 UTC, jmkiley requested changes

2020-10-02 19:53 UTC, jmkiley commented on scripts/docs-update-maps.sh
> +VERSION=${1}
Because the release tag is formatted as `ios-vX.X.X`, we should probably remove the `ios-v` at this point.

2020-10-02 19:58 UTC, katydecorah commented on scripts/docs-update-maps.sh
> +VERSION=${1}
Should do it!

```suggestion
VERSION=${1//ios-v/''}
```

2020-10-02 20:04 UTC, danswick commented on scripts/docs-update-maps.sh
> +VERSION=${1}
Heh, was just about to type this!

2020-10-02 21:02 UTC, jmkiley approved these changes
LGTM!

2020-10-03 00:18 UTC, merged

2020-10-03 01:52 UTC, jmkiley commented on circle.yml
> +            export DOCS_REPO="mapbox-gl-native-ios"
I think this should be `ios-sdk`. I tried this locally and accidentally created a docs PR in this repo.